version: '3'
 
services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: app_mysql
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user
    ports:
      - "6034:3306"
    volumes:
      - mysql8data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma8
    links:
      - mysql8
    environment:
      PMA_HOST: mysql8
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
volumes:
  mysql8data: